### ISSUE TITLE
Cut v1.0.0-rc1

### ISSUE THREAD

**Issue by glibsm** [uber-go/config#1]
Config API has been pretty stable and we should start the release cycle.

There have been a lot of commits for bug fixes and such, but all of that would fall nicely under `^1` semver.

I don't imagine we will have any changes between v1.0-rc1 and v1.0, but I don't feel 100% confident jumping straight to a full release that will lock the repo in for a long time.

Thoughts?

**Comment by alsamylkin** [comment]
Yeah, the API probably will not change, all we need to do is fix bugs.
I was thinking about adding new providers that can have a Set method, but this could be a minor version change.

**Comment by breerly** [comment]
Let's call this `1.0.0-rc1` - semver requires all 3 of the x.y.z

**Comment by breerly** [comment]
Suggest we cut all 3 libs RCs at the same time, in June.

**Comment by glibsm** [comment]
Lets first start with v0.1.0 so we can inch our way to rc's
