### ISSUE TITLE
Defaults don't appear to work with Populate

### ISSUE THREAD

**Issue by akshayjshah** [uber-go/config#16]
I'm having trouble making the `Value` type's `WithDefault` work with `Populate`. I expect this test to pass, but it doesn't:

```
func TestConfigDefaults(t *testing.T) {
        type cfg struct{ N int }

        var c cfg
        require.NoError(
                t,
                config.NewStaticProvider(nil).Get("metrics").WithDefault(cfg{42}).Populate(&c),
                "Failed to populate config.",
        )
        if c.N != 42 {
                t.Fatalf("Expected to see default N of 42, got %+v.", c)
        }
}
```

Am I using these APIs wrong, or is this a bug?

/cc @blampe (can't get your username to populate in the assignees drop-down)

**Comment by alsamylkin** [comment]
Yeah, WithDefault works only on scalar values right now, so it is very [shallow](https://github.com/uber-go/config/blob/master/value.go#L141). We can do better though and update the root provider to provide a full copy.

**Comment by akshayjshah** [comment]
Fixed!
