### ISSUE TITLE
Errors over panics

### ISSUE THREAD

**Issue by glibsm** [uber-go/config#24]
Config code panics a lot when something doesn't go it's way: can't open yaml files, can't marshal, etc.

Before start the release cycle I'd like for all the providers to return `(Provider, error)`.

For example, one of the must uses providers: `func NewYAMLProviderFromFiles(files ...string) Provider` has multiple ways it can panic.

I get that configuration loading is a pretty crucial process and more often than not, users will chose to panic right away. However, let's not make that choice for them and at least give them the option to do something else.

We're a library, and like dig, we should try very very hard to reserve panics for unexpected conditions, rather than trying to use it as an exception.

**Comment by alsamylkin** [comment]
via https://github.com/uber-go/config/pull/43
