### ISSUE TITLE
Command line provider conflicts with Cobra

### ISSUE THREAD

**Issue by bayesianmind** [uber-go/config#34]
The default config provider conflicts badly with [cobra](https://github.com/spf13/cobra):
https://github.com/uber-go/config/blob/master/config.go#L76
There's no way to easily turn off the command line provider as far as I know if you want to use the default fx fileset and env expansion logic.

This was breaking Catalyst's flags and as soon as I stopped using the command line provider Catalyst's flags came back.

**Comment by alsamylkin** [comment]
via https://github.com/uber-go/config/pull/42
