### ISSUE TITLE
config.Value should be printable to the most common formats

### ISSUE THREAD

**Issue by ghost** [uber-go/config#36]
Right now config.Value implements only `fmt.Stringer` interface simply returning `fmt.Sprint(v.Value())` which is fine for small values, but reading the entire config will be extremely hard. 

Value should implement `json.Marshaler` interface to be able to print config in a structured way. The corner case here is implementing marshaller for `map[interface{}]interface{}` which is the usual returned type used by the yaml library we use, but it is not supported by the standard library.

**Comment by akshayjshah** [comment]
Closing this, since it doesn't actually seem desirable: this makes it very, very easy to mistakenly leak secrets. We can't change the behavior of `String` without breaking back-compat, but I'd prefer to serialize configuration either as the raw input files or after populating specific structures.
