### ISSUE TITLE
Take a pass at README

### ISSUE THREAD

**Issue by glibsm** [uber-go/config#4]
Config used to be a package of the Fx framework and often sets itself up as such in the README. A pass should be taken to make sure config is viewed as a top-level library, rather than part of the framework.

I started such process by removing mentions of Fx, but there is a lot more work to do.

**Comment by mhamrah** [comment]
Please prioritize this.

**Comment by akshayjshah** [comment]
Fixed! Docs and README aren't perfect, but they're now quite a bit better.

**Comment by mhamrah** [comment]
Happy fourth!

**Comment by akshayjshah** [comment]
:rofl: Thanks, Mike!
