### ISSUE TITLE
codecov.io

### ISSUE THREAD

**Issue by glibsm** [uber-go/config#5]
Need to enable code coverage and I'd like to try out codecov.io to see how it compares with coveralls

**Comment by breerly** [comment]
Our experience w/ YARPC has been really positive:

- Uses go's native coverage file, so what you run locally is the same as codecov
- Has a really awesome PR comments, see https://github.com/yarpc/yarpc-go/pull/1051
- Has a browser plugin which shows inline which lines are covered or not:

![screen shot 2017-05-23 at 12 59 25 pm](https://cloud.githubusercontent.com/assets/263587/26373772/b31ac154-3fb7-11e7-845f-3294e3c14ba8.png)
