### ISSUE TITLE
NewYAMLProviderFromFiles signature

### ISSUE THREAD

**Issue by glibsm** [uber-go/config#51]
At the moment it's `func NewYAMLProviderFromFiles(files ...string) (Provider, error)`

Couple of things come to mind:

1. `FromFiles` typically implies `os.File`. We should consider renaming to `FromPaths`, or actually accept an `os.File`
2. Why is it a vararg method already, rather than `[]string` or `[]os.Path`? It would be a lot more flexible if we changed the signature to something like `(fils []string/os.File, ...Option)` or even ignore the `Option` part all together than can be added later.

**Comment by alsamylkin** [comment]
1. File implements an `io.ReadCloser` interface and we had a constructor to get providers from readers, but it wasn't used, so it was hidden in https://github.com/uber-go/config/pull/50
2. You don't have to create a slice manually, compiler is going to create it for you :) But you are right  in a broader sense: lots of constructors have a very long names and too specific, we should definitely push this number lower via options.

**Comment by akshayjshah** [comment]
Ship has sailed on this, not fixable in 1.x series.
