### ISSUE TITLE
[Regression] Populate attempts to unmarshal keys that aren't in the provider

### ISSUE THREAD

**Issue by bayesianmind** [uber-go/config#55]
In previous versions of config values where HasValue == false were never deserialized (theory, haven't confirmed that). In 1.0.0 every field is getting deserialized, even if it has no corresponding value in the yaml.

This breaks deserializing into a struct like xtchannel.Configuration which contains `UnmarshalText` methods that don't accept default values as valid.

**Comment by alsamylkin** [comment]
Via https://github.com/uber-go/config/pull/56
