### ISSUE TITLE
android arm build overflow

### ISSUE THREAD

**Issue by ghost** [uber-go/config#61]
From https://github.com/uber-go/fx/issues/594
`GOOS=android GOARCH=arm CGO_ENABLED=0 go build` fails to compile:
```
./decoder.go:76: constant 9223372036854775807 overflows uintptr
./decoder.go:122: constant 18446744073709551615 overflows uintptr
```

**Comment by akshayjshah** [comment]
We're not planning to fix this; if we ever need to deploy on ARM and/or Android, we can look into it.
